### ISSUE TITLE
remote-builder doesn't share info in volumes

### ISSUE THREAD

**Issue by SamosadovArtem** [GoogleCloudPlatform/cloud-builders-community#129]
As I understand cloud-build use "workspace" directory as a volume, but when I download files and save it into this folder them doesn't exist on next steps. Could you please take a look at this?

**Comment by codrienne** [comment]
You're right that Cloud Build uses a directory named /workspace  as a volume. It is also used as the working directory. You don't need to specify the directory "/workspace" in your buildstep arguments, because "/workspace" is the current directory "."

    steps:
    - name: 'bash'
      args: ['-c', 'echo "I am a file in /workspace" > foo.txt']

Anything in workspace should persist from step to step. Can you share your cloudbuild.yaml?

You can read more about Cloud Build volumes and working directories here: https://cloud.google.com/cloud-build/docs/build-config#build_steps

**Comment by SamosadovArtem** [comment]
Hello @codrienne
Thanks for the quick feedback.
Please find my cloudbuild.yaml bellow:
```
steps:
- name: gcr.io/machinaseptember2016/remote-builder
  env:
  - COMMAND=sudo bash workspace/ping.bash
  - ZONE=us-east1-b
  - INSTANCE_NAME=remote-cloud-build
  - INSTANCE_ARGS=--image-project centos-cloud --image-family centos-7
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/${PROJECT_NAME}/${IMAGE_NAME}', '.']

...[other steps]
```

In the ping.bash file I download python dependencies from private repository and save it into the workspace/lib folder. On the next step, during the image creation, I try to get this libraries but they are not exist in this folder
