### ISSUE TITLE
Firebase: Example doesn't work due to underscore in variable name

### ISSUE THREAD

**Issue by nieldw** [GoogleCloudPlatform/cloud-builders-community#145]
The current firebase builder example doesn't work because of the underscore in `FIREBASE_TOKEN`, due to https://github.com/GoogleCloudPlatform/cloud-builders/issues/413

It currently fails with `ERROR: (gcloud.builds.submit) INVALID_ARGUMENT: invalid build: invalid .secrets field: secretEnv "FIREBASE_TOKEN" is used without being defined`

A work-around is to use sentence case for the part of the variable after the underscore. Here's what the example would look like:
```
steps:
- name: 'gcr.io/valr-ci/firebase'
  entrypoint: /bin/bash
  args: ['-c', 'firebase list --token $$FIREBASEToken']
  secretEnv: ['FIREBASEToken']
secrets:
- kmsKeyName: 'projects/[PROJECT_ID]/locations/global/keyRings/cloudbuilder/cryptoKeys/firebase-token'
  secretEnv:
    FIREBASE_TOKEN: '<ENCRYPTED_TOKEN>'
```

---
```
$ gcloud --version
Google Cloud SDK 224.0.0
bq 2.0.36
core 2018.11.02
gsutil 4.34
```
cc @petomalina @ImJasonH
