### ISSUE TITLE
How to replace slashes in the branch name

### ISSUE THREAD

**Issue by timini** [GoogleCloudPlatform/cloud-builders-community#184]
Git branches uses names like `feature/new-feature`, the slash is incompatible with docker image tags so i want to use a regex (or other means) to replace the slash in the $BRANCH_NAME with an underscore. This is possible in bash using the following:

```
BRANCH_NAME=feature/test echo ${BRANCH_NAME/\//_}
```

is there any way to create an env variable with the branch name escaped?

**Comment by timini** [comment]
It looks like this is a possible solution

```
steps:
  - id: test
    name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-exc"
      - |
        echo ${BUILD_ID//-/_}
    env:
      - "BUILD_ID=$BUILD_ID"
```
I wonder if there is a better way?

**Comment by timini** [comment]
```
steps:
  - id: test
    name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-exc"
      - |
        echo ${BRANCH_NAME//\//_}
    env:
      - "BRANCH_NAME=feature/test"
```
output:
```
+ echo feature_test
feature_test
```

**Comment by trenslow** [comment]
Hi @timini, did you ever find an elegant solution for this problem?

**Comment by jachinte** [comment]
In case anyone is still looking for this, here is a complete example:

```yaml
steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args: [ "-c", "_TMP_VAR=`echo $BRANCH_NAME | sed -r 's,/,-,g'`; docker build -t gcr.io/$PROJECT_ID/$REPO_NAME:$_NEW_BRANCH_NAME ."]
substitutions:
  _NEW_BRANCH_NAME: $_TMP_VAR
images:
  - "gcr.io/$PROJECT_ID/$REPO_NAME"
```

**Comment by groudjulien** [comment]
Hi @jachinte do your answer still works ? 
I try this but $_NEW_BRANCH_NAME is empty
```
steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args: [ "-c", "_TMP_VAR =`echo $BRANCH_NAME | sed -r 's,/,-,g'`; echo '1'; echo $_NEW_BRANCH_NAME; echo '2'; docker build -t gcr.io/$PROJECT_ID/$REPO_NAME:$_NEW_BRANCH_NAME ."]
substitutions:
  _BRANCH_FINAL_NAME: $_TMP_VAR
```
I got this logs
```
1

2
```
And an error for the build. Do you have any idea ?
