### ISSUE TITLE
Docker compose mounted volumes empty

### ISSUE THREAD

**Issue by tomatosource** [GoogleCloudPlatform/cloud-builders-community#207]
## Affected builder image

`gcr.io/cloud-builders-community/docker-compose`

## Expected Behavior

Current directory volumes mounted via `docker-compose.yml` to not be empty.

## Actual Behavior

Mounted volume is empty.

## Steps to Reproduce the Problem
`cloudbuild.yaml`
```
steps:

- name: 'docker.io/tomatosource/docker-compose'
  id: test
  args:
    - 'up'
    - '--force-recreate'
    - '--abort-on-container-exit'
    - '--exit-code-from'
    - 'app'
  timeout: '300s'
```

`docker-compose.yml`
```
version: '3.5'

services:
  app:
    image: golang:alpine
    volumes:
      - .:/foo
    working_dir: /foo
    command: ls
```

## Additional Info

Running locally via `cloud-build-local --config=cloudbuild.yaml --dryrun=false .`

**Comment by truthmast** [comment]
I've also been running into this issue lately and couldn't track down the cause. It works fine running in the Cloud, but local doesn't seem to mount volumes correctly. Usually it's empty, but one of my services has a few of the sub-folders visible. However, those sub-folders are also empty. I've tried relative and absolute paths.

I've also tried defining volumes separately (after the `steps:` section). Doing it this way creates a file-not-found error at least:
```
volumes:
  data:
    driver_opts:
      type: none
      device: /path-to-data
      o: bind
```

**Comment by amalhotragannett** [comment]
Is there a work-around for this solution?

**Comment by jgedarovich** [comment]
bump - also ran into this bug

**Comment by JackCA** [comment]
@Philmod  sorry to ping, but wondering if you have thoughts on this? 

Maybe you have an idea of root cause?

**Comment by samhiatt** [comment]
I've ran into this issue as well, except with images based on 'gcr.io/cloud-builders/docker'. I was able to get mounted volumes to show up in 'gcr.io/cloud-builders/gsutil' layers, but only if I first include a step that calls `docker run`, explicitly mounting the volumes like this:
```
  - name: 'gcr.io/cloud-builders/docker'
    args: [ "run", "--rm", "-v", "vol1:/output", "gcr.io/$PROJECT_ID/tdc:latest"]
    volumes:
      - name: 'vol1'
        path: '/output'
```
Then the following step will correctly list the expected contents of /output:
```
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: "bash"
    args: [ "-c", "ls", "-l", "/workspace" ]
    volumes:
      - name: 'vol1'
        path: '/output'
```
However, the mounted volume /workspace is empty in the image 'cloud-builders-community/firebase', for example if I include a step like this:
```
  - name: 'gcr.io/$PROJECT_ID/firebase'
    entrypoint: 'bash'
    args: ['-c', 'ls', '-l', '/output', '.']
    volumes:
      - name: 'vol1'
        path: '/output'
```
I'm not sure if there's something I'm doing wrong or if it's a bug. Any help would be appreciated.
