### ISSUE TITLE
sonarqube with sonarcloud.io

### ISSUE THREAD

**Issue by jonbcampos-alto** [GoogleCloudPlatform/cloud-builders-community#210]
## Affected builder image
gcr.io/cloud-builders-community/sonarqube

## Expected Behavior
successful build

## Actual Behavior
```
Step #2: START: Running sonar-scanner-cli on Tue Mar 19 20:26:02 UTC 2019
Step #2: INFO: Scanner configuration file: /opt/sonar-scanner-3.2.0.1227-linux/conf/sonar-scanner.properties
Step #2: INFO: Project root configuration file: NONE
Step #2: INFO: SonarQube Scanner 3.2.0.1227
Step #2: INFO: Java 1.8.0_201 Oracle Corporation (64-bit)
Step #2: INFO: Linux 4.15.0-1028-gcp amd64
Step #2: INFO: User cache: /root/.sonar/cache
Step #2: INFO: ------------------------------------------------------------------------
Step #2: INFO: EXECUTION FAILURE
Step #2: INFO: ------------------------------------------------------------------------
Step #2: INFO: Total time: 1.148s
Step #2: INFO: Final Memory: 4M/56M
Step #2: INFO: ------------------------------------------------------------------------
Step #2: ERROR: Error during SonarQube Scanner execution
Step #2: ERROR: null
Step #2: ERROR: Caused by: Could not initialize NSS
Step #2: ERROR: Caused by: /usr/lib/libnss3.so
Step #2: ERROR: 
Step #2: ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.
```
## Steps to Reproduce the Problem

1. build image from source
2. add build step to cloudbuilder
3. run with the following options
```yaml
  - name: "gcr.io/my-project/sonar-scanner:latest"
    args:
      - '-Dsonar.projectKey={projectKey}'
      - '-Dsonar.organization={organization}'
      - '-Dsonar.sources=src'
      - '-Dsonar.host.url=https://sonarcloud.io'
      - '-Dsonar.login={token}'
      - '-Dsonar.exclusions=node_modules/**'
      - '-Dsonar.typescript.lcov.reportPaths=coverage/lcov.info'
      - '-Dsonar.coverage.exclusions=src/**/*.spec.ts'
    dir: "functions"
```
## Additional Info
This works if I run from my local computer, just fails in cloudbuilder
