### ISSUE TITLE
kaniko: failed to find one or more images after execution of build steps

### ISSUE THREAD

**Issue by sh** [GoogleCloudPlatform/cloud-builders-community#212]
## Affected builder image

`gcr.io/cloud-builders-community/kaniko`

## Expected Behavior

When building images with `kaniko` in `cloudbuild.yaml` the `images` should be found at the end of the build.

`cloudbuild.yaml`

```yaml
steps:
  # Build image and push to gcr with kaniko
  - name: gcr.io/kaniko-project/executor:latest
    args: [
      "--context=/workspace/api",
      "--destination=gcr.io/<$PROJECT_ID>/api:latest",
      "--destination=gcr.io/<$PROJECT_ID>/api:$SHORT_SHA",
      "--cache=true",
      ]

# List built images in cloudbuild history
images:
  - "gcr.io/<$PROJECT_ID>/api:$SHORT_SHA"
  - "gcr.io/<$PROJECT_ID>/api:latest"

tags: ["$BRANCH_NAME"]
```

## Actual Behavior

The images have been pushed to `Container Registry` and can be deployed via `kubectl`.

The cloudbuild fails with error that images cannot be found:
```
ERROR: failed to find one or more images after execution of build steps: 
["gcr.io/<$PROJECT_ID>/api:a4a36cd", "gcr.io/<$PROJECT_ID>/api:latest"]
```

## Steps to Reproduce the Problem

1. Use the `kaniko-project/executor` builder in `cloudbuild.yaml`
2. Add `images` section to `cloudbuild.yaml` that verifies / pushes the images
3. Trigger build

## Additional Info

We're currently using docker to build our containers and wanted to give kaniko a shot, it compiles much faster 🎉  but it seems there is a mismatch how the `images` section is handled when images are not being built by docker.

**Comment by ImJasonH** [comment]
When using Kaniko you don't have to list the images in the build's `images` field since Kaniko already pushes them itself.

That error message indicates the build environment doesn't have those images locally so it can't push them, because Kaniko already pushed them directly, skipping local storage.

**Comment by ImJasonH** [comment]
I'll make sure we document this better since it can definitely be confusing.

**Comment by sh** [comment]
Thanks for coming back so quickly @ImJasonH 

Is there a way to inform cloudbuild that these images were produced so they'll show up as image artifacts in the cloudbuild history?

**Comment by ImJasonH** [comment]
I'm working on adding this now, since other users of Kaniko have also previously asked. No definite timeline, but it's on my radar.

**Comment by Sexual** [comment]
@ImJasonH Any update regarding this? It is frustrating not having it displayed in the dashboard

**Comment by pegex-dev** [comment]
^ same I just ran into this issue and found this issue.

**Comment by LanceSandino** [comment]
^ same I just ran into this issue and found this issue.

**Comment by jeremyschlatter** [comment]
I just ran into this as well. For future folks who want kaniko builds to display nicely in the Google Cloud dashboard, I came up with this very hacky solution:

```yaml
steps:
# Build with kaniko.
- name: gcr.io/kaniko-project/executor:latest
  args:
  - --destination=$_IMAGE/kaniko:$COMMIT_SHA
  - --cache=true
  - --cache-ttl=48h

# Hacky docker stuff so we can get build info.
- name: docker
  args: [pull, $_IMAGE/kaniko:$COMMIT_SHA]
- name: docker
  args: [tag, $_IMAGE/kaniko:$COMMIT_SHA, $_IMAGE:$COMMIT_SHA]
- name: docker
  args: [push, $_IMAGE:$COMMIT_SHA]

# Deploy.
- name: gcr.io/cloud-builders/gcloud
  args: [run, deploy, my-service, --image=$_IMAGE:$COMMIT_SHA]
  
substitutions:
  _IMAGE: my-image-name

images: [$_IMAGE:$COMMIT_SHA]
```

Explanation:

- We need the `images` field to be set so we can see it nicely in the dashboard.
- That means we need the image to be present locally, because as mentioned above Cloud Build will try to push this image and kaniko did not leave it present in local storage. So we pull it with `docker pull`.
- Now the weirdest (to me) part: if you `docker pull` and then `docker push` the image that kaniko built, you will get a different image digest, and so it will still not show up nicely in the dashboard. I'm very confused about this, but you can work around it thusly:
- Use `docker tag` to _rename the image_. kaniko will manipulate images named `$_IMAGE/kaniko`, but from Cloud Build's perspective you end up with just `$_IMAGE`.

Note that depending on your purposes, you may be able to simplify this. For example if you don't need to immediately deploy to Cloud Run or whatever, you can probably skip the `docker push` step, since `images` will do that for you:

```yaml
steps:
# Build with kaniko.
- name: gcr.io/kaniko-project/executor:latest
  args:
  - --destination=$_IMAGE/kaniko:$COMMIT_SHA
  - --cache=true
  - --cache-ttl=48h

# Hacky docker stuff so we can get build info.
- name: docker
  args: [pull, $_IMAGE/kaniko:$COMMIT_SHA]
- name: docker
  args: [tag, $_IMAGE/kaniko:$COMMIT_SHA, $_IMAGE:$COMMIT_SHA]
  
substitutions:
  _IMAGE: my-image-name

images: [$_IMAGE:$COMMIT_SHA]
```

And you might also be able to skip the renaming step, if you understand what's going on here better than I do.

Hope this helps!
