### ISSUE TITLE
Helm Cloud-builder doesn't work with /bin/bash entrypoint

### ISSUE THREAD

**Issue by ttfreeman** [GoogleCloudPlatform/cloud-builders-community#322]
I am testing `cloud-builders-community/helm` in cloudbuild.yaml and while it is working with `args: ['list']` , it doesn't work when I use an entry point such as `/bin/bash`. The following step in cloudbuild results in an error:

```
steps:
- name: 'gcr.io/$PROJECT_ID/helm'
  id: Test & Deploy Helm Chart, Test Deploy
  entrypoint: /bin/sh
  args: 
  - '-c'
  - |
    helm list --history-max 200 --service-account tiller
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=?????'
  - 'CLOUDSDK_CONTAINER_CLUSTER=?????'
```
Error:

```
Creating /builder/home/.helm
Creating /builder/home/.helm/repository
Creating /builder/home/.helm/repository/cache
Creating /builder/home/.helm/repository/local
Creating /builder/home/.helm/plugins
Creating /builder/home/.helm/starters
Creating /builder/home/.helm/cache/archive
Creating /builder/home/.helm/repository/repositories.yaml
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com
Adding local repo with URL: http://127.0.0.1:8879/charts
$HELM_HOME has been configured at /builder/home/.helm.
Error: error installing: Post http://localhost:8080/apis/extensions/v1beta1/namespaces/kube-system/deployments: dial tcp 127.0.0.1:8080: connect: connection refused
ERROR
ERROR: build step 0 "gcr.io/cosmic-shift-196717/helm" failed: exit status 1
```

## Affected builder image

`gcr.io/cloud-builders-community/helm`

## Expected Behavior
to list helm releases
## Actual Behavior
throws an error when using entry point but it works with `args: ['list]
## Steps to Reproduce the Problem

1. just run the following step with cloud builkd:
```
steps:
- name: 'gcr.io/$PROJECT_ID/helm'
  id: Test & Deploy Helm Chart, Test Deploy
  entrypoint: /bin/sh
  args: 
  - '-c'
  - |
    helm list --history-max 200 --service-account tiller
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=?????'
  - 'CLOUDSDK_CONTAINER_CLUSTER=?????'
```
