### ISSUE TITLE
docker-compose takes much time on cloudbuild however I increased machineType

### ISSUE THREAD

**Issue by xmarcoied** [GoogleCloudPlatform/cloud-builders-community#370]
## Affected builder image

`gcr.io/cloud-builders-community/docker-compose`

I use cloud-builder-communitry docker-compose image to run django unittests, and it runs much slower on the cloud however I increased the machineType to (N1_HIGHCPU_8 , N1_HIGHCPU_32) 

It takes on my machine (Intel(R) Core(TM) i7-4600M CPU @ 2.90GHz) :7m48.115s 
And on cloudbuild: 15m18.019s and sometimes +20m

Solutions I tried: 
- Assigning CPUs to each docker-compose service
- Running django tests [in parrallel](https://docs.djangoproject.com/en/3.0/topics/testing/overview/#running-tests-in-parallel)

What would you recommend to optimize my implementation?

Example of docker-compose cloudbuild step I use: 
```
- name: gcr.io/${PROJECT_ID}/docker-compose
  id: run_tests
  args: ['-f' , 'docker/docker-compose.yml' , 'up' , '--abort-on-container-exit' , '--exit-code-from' , 'django']
```

Example of dockercompose.yaml:
```
version: '2.2'
services:
    redis:
        image: redis
        expose:
            - 6379
    postgres:
        image: postgres:9.6-alpine
        command: -c max_connections=3000 -c fsync=off -c synchronous_commit=off -c full_page_writes=off -c max_locks_per_transaction=64
        tmpfs:
            - /var/lib/postgresql
    datastore:
        image: registry.hub.docker.com/google/cloud-sdk
        entrypoint: bash
        command: gcloud beta emulators datastore start --host-port=datastore:8081
    pubsub:
        image: registry.hub.docker.com/google/cloud-sdk
        entrypoint: bash
        command: gcloud beta emulators pubsub start --host-port=pubsub:8085
    django:
        entrypoint: bash
        image: gcr.io/turing-striker-251910/base-image-python
        command: >
            -c "
            coverage run ./manage.py test -v 0 core.tests --noinput --parallel &&
            coverage combine &&
            coverage report &&
            coverage xml"
        depends_on:
            - pubsub
            - datastore
            - redis
            - postgres
```
