### ISSUE TITLE
windows-builder: transmit several files to the Windows VM very slowly

### ISSUE THREAD

**Issue by poy** [GoogleCloudPlatform/cloud-builders-community#375]
## Affected builder image

(e.g., `gcr.io/cloud-builders-community/helm`)

windows-builder

## Expected Behavior

Quickly transmits workspace to remote VM.

## Actual Behavior

Does so at a very slow rate.

### Experiment

1. To simulate several source code files, create several files that are ~1KiB each:
```bash
for i in $(seq 1 ${NUM_FILES}); do printf 'x%.s' {1..1024} >> testdata-$i; done
```

2. Create cloud build configuration and windows bat file to run:

cloudbuild.yaml
```yaml
steps:
- name: 'gcr.io/$PROJECT_ID/windows-builder'
  args: [ '--command', 'C:\workspace\hello.bat' ]
tags: ['cloud-builders-community']
```

hello.bat:
```bat
echo Hello World!
```

3. Time and execute build:
```bash
time gcloud builds submit --config cloudbuild.yaml
```

### Results

| NUM_FILES | Time (seconds) |
|:---------:|:--------------:|
|     1     |       264      |
|     10    |       311      |
|    100    |       560      |
