### ISSUE TITLE
Windows builder : Environment variables not accessible in powershell script

### ISSUE THREAD

**Issue by manjuprabhuv** [GoogleCloudPlatform/cloud-builders-community#414]
## Affected builder image

(e.g., `gcr.io/cloud-builders-community/helm`)
https://github.com/GoogleCloudPlatform/cloud-builders-community/tree/master/windows-builder
## Expected Behavior
Environment variable values set in cloudbuild.yml must be accessible inside PowerShell script
## Actual Behavior
Environment variables does seem to be set inside the container.  
## Steps to Reproduce the Problem
cloudbuild.yaml content
```YAML
    - name: 'gcr.io/$PROJECT_ID/windows-builder'
      args: [ '--command', 'powershell.exe -file build.ps1' ]
      env:
      - 'ZONE_VALUE=test_var_value'
```
Expected `ZONE_VALUE` to be printed, but looks like it is not set. 
```
Get-ChildItem Env:
echo  $env:ZONE_VALUE
```
However, I can see it in execution details - 
![image](https://user-images.githubusercontent.com/2736597/82207615-76a0c280-994d-11ea-8ba5-da4ae1a376e7.png)
