### ISSUE TITLE
firebase functions:config:set fails due to permission issue

### ISSUE THREAD

**Issue by gbhojak** [GoogleCloudPlatform/cloud-builders-community#428]
## Affected builder image

( `gcr.io/cloud-builders-community/firebase`)

## Expected Behavior

With following cloudbuild.yaml:
```

steps:
- name: node
  entrypoint: npm
  args: ['install']
  dir: 'functions'
-name: 'gcr.io/$PROJECT_ID/firebase'
  args: ['functions:config:set', 'somekey=${_SOME_KEY}']
- name: 'gcr.io/$PROJECT_ID/firebase'
  args: ['deploy', '--project=${_PROJECT}', '--only=functions']
  dir: 'functions'
substitutions:
    _PROJECT: $PROJECT_ID # default value
   _SOME_KEY: somevalue

```
the config variable/value specified in functions:config:set' should set the config value and the build should proceed to deploy step.

## Actual Behavior

The build throws following error:

```
Using default tag: latest
latest: Pulling from <project_id>/firebase
81fc19181915: Already exists
ee49ee6a23d1: Already exists
828510924538: Already exists
a8f58c4fcca0: Already exists
33699d7df21e: Already exists
923705ffa8f8: Already exists
ae06f9217656: Already exists
39c7f0f9ab3c: Already exists
df076510734b: Already exists
1448deae4408: Pulling fs layer
f6f3265bc9d0: Pulling fs layer
f6f3265bc9d0: Verifying Checksum
f6f3265bc9d0: Download complete
1448deae4408: Verifying Checksum
1448deae4408: Download complete
1448deae4408: Pull complete
f6f3265bc9d0: Pull complete
Digest: sha256:1159a3fdff9d483cb37c36e9972863e6e3801e7eb2264390f7ccc6ff36fa9859
Status: Downloaded newer image for gcr.io/<project_id>/firebase:latest
gcr.io/<project_id>/firebase:latest

Error: HTTP Error: 403, The caller does not have permission
```

## Steps to Reproduce the Problem

1.
The cloud build service account has following roles

- Cloud Build Service Account
- Cloud Functions Admin
- Cloud Functions Developer
- Editor
- Firebase Admin
- Service Account Token Creator
- Service Account User
- Cloud Run Admin
- API Keys Admin
- Service Usage Admin

2.
Execute a build through Cloud Build triggers

## Additional Info

I have deployed firebase hosting and other resources for the backend with above cloud build permissions. But this seems to be failing for some reason.
