### ISSUE TITLE
./gradlew permission denied

### ISSUE THREAD

**Issue by astro-wolf** [GoogleCloudPlatform/cloud-builders-community#487]
## Affected builder image
gcr.io/cloud-builders-community/android

## Expected Behavior
```
  - name: 'gcr.io/$PROJECT_ID/android:29'
    id: build
    args: ['./gradlew', 'assembleDebug']
    env:
      - 'TERM=dumb'
      - 'JAVA_TOOL_OPTIONS="-Xmx3g"'
      - 'GRADLE_USER_HOME=/build_cache/.gradle'
      - 'GRADLE_OPTS="-Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dkotlin.incremental=false"'
      - 'BRANCH_NAME=$BRANCH_NAME'
    waitFor: ['extract_build_cache']
    volumes:
      - name: 'build_cache'
        path: '/build_cache'
```
The step above should run and output an apk.

## Actual Behavior
This is actually throwing the following error:

`Step #2 - "build": /bin/run_build: line 13: ./gradlew: Permission denied`

## Steps to Reproduce the Problem

1. Clone the cloud-builders-community project.
2. Deploy builders from /android
3. Copy all the code from [simple-cloudbuild.yaml](https://github.com/GoogleCloudPlatform/cloud-builders-community/blob/master/android/examples/simple-cloudbuild.yaml).
4. Create buckets as per documentation.
5. Run the trigger.

## Additional Info
I have kept all the steps same. Except the sdk version and bucket name, there are no other changes to `.yaml` file.
