### ISSUE TITLE
Windows Builder Error "The system cannot find the path specified"

### ISSUE THREAD

**Issue by isrhedden** [GoogleCloudPlatform/cloud-builders-community#556]
## Affected builder image

gcr.io/cloud-builders-community/windows-builder

## Expected Behavior

This should build and push a Windows container to my Container Registry for my Kubernetes application

## Actual Behavior

The trigger completes without an explicit error, but it doesn't initiate the docker build & push. No update has been made in Container Registry. The closest thing I can find to an error message is "The system cannot find the path specified." Screenshot below:
![Error Message](https://i.stack.imgur.com/eStq2.png)

## Steps to Reproduce the Problem

I structured my code based on Google's [docker-windows example](https://github.com/GoogleCloudPlatform/cloud-builders-community/tree/master/windows-builder/images/docker-windows). Here is my repository file structure:
```    
 repository
   cloudbuild.yaml
   builder.ps1
   worker
      Dockerfile
```

Here is my cloudbuild.yaml:
```
steps:
# WORKER
- name: 'gcr.io/[my-project-id]/windows-builder'
  args: [ '--create-external-ip', 'true', '--command', 'powershell.exe -file build.ps1' ]

# OPTIONS
options:
  logging: CLOUD_LOGGING_ONLY
```

Here is my build.ps1:
```
docker build -t gcr.io/[my-project-id]/test-worker ./worker;
if ($?) {
  docker push gcr.io/[my-project-id]/test-worker;
}
````

Here is my worker Dockerfile:
```
FROM gcr.io/[my-project-id]/test-windows-node-base:onbuild
```

## Additional Info
The container, gcr.io/[my-project-id]/windows-builder definitely exists, and it's located in the same GCP project as the Cloud Build trigger, just as the windows-builder documentation commanded. I'm guessing that it's unable to find either my build.ps1 file or my worker Dockerfile. I can't understand why, though.

Does anybody know what I'm doing wrong here? Any help would be appreciated.

**Comment by isarkis** [comment]
* You can ignore 'The system cannot find the path specified'.  I use windows-builder and get this message every time.  
* Why are you using '--create-external-ip' option?  That option is to be used only in those cases where internal network is used, but even then it doesn't take 'true' or 'false' - it's just a flag.  
* Your powershell filename is builder.ps1 but you are calling build.ps1

Can you try changing cloudbuild.yaml to something like so?

```
steps:
# WORKER
- name: 'gcr.io/app-exodus/windows-builder'
  args: [ '--command', 'powershell.exe -file builder.ps1' ]

# OPTIONS
options:
  logging: CLOUD_LOGGING_ONLY
```

**Comment by isrhedden** [comment]
> * You can ignore 'The system cannot find the path specified'.  I use windows-builder and get this message every time.
> * Why are you using '--create-external-ip' option?  That option is to be used only in those cases where internal network is used, but even then it doesn't take 'true' or 'false' - it's just a flag.
> * Your powershell filename is builder.ps1 but you are calling build.ps1
> 
> Can you try changing cloudbuild.yaml to something like so?
> 
> ```
> steps:
> # WORKER
> - name: 'gcr.io/app-exodus/windows-builder'
>   args: [ '--command', 'powershell.exe -file builder.ps1' ]
> 
> # OPTIONS
> options:
>   logging: CLOUD_LOGGING_ONLY
> ```

Thank you for the speedy response!

- Ok, good to know. It's the only thing that looks like an error so I latched onto it.
- I'm using this flag because without it I was experiencing [this](https://stackoverflow.com/questions/70385128/google-cloud-build-windows-builder-error-failed-to-get-external-ip-address-cou) error. --create-external-ip got rid of the issue, but I'll be honest in that I don't fully understand why. Perhaps this is the real issue, after all.
- That's a typo. I updated my post to say build.ps1.

I tried your change and went back to [this](https://stackoverflow.com/questions/70385128/google-cloud-build-windows-builder-error-failed-to-get-external-ip-address-cou) error. It's the same error from the second bullet listed above. Any idea of what's happening?

**Comment by isarkis** [comment]
Looks like a bug to me, I will create a PR to fix that.  Until then, you want to use '--create-external-ip' flag.

**Comment by isrhedden** [comment]
> Looks like a bug to me, I will create a PR to fix that. Until then, you want to use '--create-external-ip' flag.

Ok great, thank you! But that still brings me back to my original issue. My pipeline isn't building anything and the only message that looks anything like an error is "The system cannot find the path specified". Does anybody know what's going on?

**Comment by isarkis** [comment]
I suspect something is wrong with powershell script being executed, can you change your cloudbuild.yaml to something like so and see if 'dir' command gets executed?

```
steps:
# WORKER
- name: 'gcr.io/[my-project-id]/windows-builder'
  args: [ '--create-external-ip', '--command', 'dir' ]

# OPTIONS
options:
  logging: CLOUD_LOGGING_ONLY
```

**Comment by isrhedden** [comment]
That's a good idea. I tried this and the 'dir' command did execute. In the build logs I can see the contents of my root directory, including build.ps1. Let me know if you have an idea of where to go from here.

**Comment by isarkis** [comment]
I would try to something like 'timeout 1600' which should give you enough time to RDP to the Windows GCE instance to see if your powershell script is on the machine and if you can launch it manually.  Being new to the powershell,  I remember running into lots of different annoying issues with it.

Another thing you should probably do is use newer 2019 image, the default image used by the windows-builder is outdated.  I use projects/windows-cloud/global/images/windows-server-2019-dc-core-for-containers-v20211012.

**Comment by isrhedden** [comment]
Your post from yesterday gave me an idea. I put back my original code, but tried simply removing the "true" parameter from the cloudbuild.yaml. To my surprise, this worked!

Thank you for all your help! Below is the working code:

```
steps:
# WORKER
- name: 'gcr.io/app-exodus/windows-builder'
  args: [ '--create-external-ip', '--command', 'powershell.exe -file build.ps1' ]

# OPTIONS
options:
  logging: CLOUD_LOGGING_ONLY
```
