### ISSUE TITLE
Problems deploying Firebase Functions

### ISSUE THREAD

**Issue by runa** [GoogleCloudPlatform/cloud-builders-community#675]
## Affected builder image

`gcr.io/cloud-builders-community/firebase`

## Expected Behavior

The instructions to deploy 'hosting' [seem to be super simple](https://cloud.google.com/build/docs/deploying-builds/deploy-firebase#continuous_deployment), just:
```
        args: ['deploy', '--project=project-id', '--only=hosting']
```

Now, I wanted to deploy hosting and functions, so I stripped the '--only=hosting' but this failed because:
1. the `venv` was not found (nor created automatically)
2. `pip install` was missing
3. environment variables were missing (from the cloud build step definition) 

## Steps to Reproduce the Problem

1. use the builder to deploy a sample function (not hosting)

## Additional Info
This is the cloudbuild.yml I ended up using to deploy my firebase function using cloud build:
```
steps:
  - name: gcr.io/XXX/firebase
    env:
      - ENV1=1
    args:
      - '-c'
      - |
        set  &&
        env | grep -E "ENV1|SECRETENV" > functions/.env &&
        python3 -m venv functions/venv &&
        . functions/venv/bin/activate &&
        python -m pip install -r functions/requirements.txt &&
        firebase deploy --project=XXXX
    dir: blah
    entrypoint: /bin/bash
    secretEnv:
      - SECRETENV
timeout: 600s
availableSecrets:
  secretManager:
    - versionName: projects/XXX/secrets/XXXX/versions/latest
      env: SECRETENV
```
